### ISSUE TITLE
User friendly navigation and responsive design (must-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#1]
**User story 1** 

As a client, I need a simple and easy navigation and a user-friendly design that is a responsive layout for my device so I can find information easily and quickly.

**Acceptance Criteria**

- [x] The website is fully responsive across various devices and screen sizes.
- [x] The navigation bar is displayed clearly on the top of the page.

**Tasks**

- [x] Add responsive design principles using Bootstrap to ensure the website is accessible on different devices.
- [x] Arrange the site layout and navigation based on best practices, ensuring all sections and pages are easily accessible.
