### ISSUE TITLE
Engaging descriptions, programs and images of the spa (must-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#2]
**User story 2** 
As a new client, I want to see images and detailed information about the spa ambience and some of the available programs so that I can decide if It is the right place for me to give it a try.

**Acceptance Criteria**

- [x] The homepage has a carousel with images of the spa ambience, massage therapists and some programs that rotate automatically. 
- [x] Have engaging descriptions of the spa and some programs are displayed clearly within the website's content.
- [x] The homepage layout prominently features the images and descriptions in an clean and orderly manner.

**Tasks**

- [x] Embedded to provide images of the spa ambience, massage therapists and some programs in the homepage using a carousel.  
- [x] Provided engaging descriptions for the spa’s history and ambiance within the site’s content.
- [x] Design and implement a homepage layout that prominently features the images and descriptions.
