### ISSUE TITLE
Location, contact details and opening hours (must-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#3]
**User story 3**

As a prospective client, I need to find essential information about location, contact details and opening hours clearly and concisely so I can plan my visit or contact the spa.

**Acceptance Criteria**

- [x] The website contains a dedicated section for location, contact details, and opening hours.
- [x] This section is clearly visible and accessible from all parts of the website.

**Tasks**

- [x] Design and add a section for location, contact details, and opening hours.
- [x] Ensure the contact section is clearly visible and accessible from all pages of the website, regarding common design standards.
