### ISSUE TITLE
All massage programs displayed on a separate Massage Programs page - (must-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#4]
**User story 4**

As a potential client, I want to view all the programs in detail on the website  so I can match my needs and decide which program I should do.

**Acceptance Criteria**

- [x] The website has a separate page for the list of massage programs.
- [x] The massage programs page uses the Bootstrap grid and card components for consistency in layout and responsiveness.
- [x] Each card shows the massage program name, image, description, duration and price.

**Tasks**

- [x] Create a responsive Massage Program page featuring all programs and their relevant details.
