### ISSUE TITLE
Booking Form and Success page (must-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#5]
**User Story 5** 

As a regular client, I want to book the service on the website so that I can reserve my date and time in my schedule.

**Acceptance Criteria**

- [x] A booking form is easy to find, and the form is simple and easy to use.
- [x] The booking form includes all necessary information about the client: New/old member, Name, Email, Phone Number, Which program and message. 8 Programs are: Thai massage 60 min, Swedish massage 60 min, Hot stone massage 60 min, Deep Tissue massage 60 min, Sports massage 60 min, Aromatherapy massage 60 min, Foot massage 60 min, Couples massage 80 min. Date and time and message box.
- [x] All fields (except. the message box) on the form must be filled before the user can submit the form.
- [x] When the form is filled correctly, the user is taken to a success page.

**Tasks**

- [x] Implement a booking form on the website.
- [x] Implement HTML validation on the form to fit the requirements above.
- [x] Create a success page to direct users to after submitting the form.
