### ISSUE TITLE
Special discount section and a membership form (should-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#6]
**User Story 6** 
As a massage lover, I want to see if there are special discounts for a member or any promotions, so I can decide if I want to be a member to plan my visit within my budget.

**Acceptance Criteria**

- [ ] Special discount for member and other promotions information on the home page before the footer.
- [ ] Membership signup  button.

**Tasks**

- [ ] Display a special discount for a member and other promotions information.
- [ ] Create a membership button link to the signup form.
