### ISSUE TITLE
Testimonials (could-have)

### ISSUE THREAD

**Issue by Chatlada-Nina** [Chatlada-Nina/serenity-relax-and-spa#7]
**User story 7**
As a prospective client, I want to read testimonials from previous clients so that I can feel more confident about booking a program.

**Acceptance Criteria**

- [x] The testimonials page displays at least 3 client testimonials.
- [x] Each testimonial must have the client’s name, picture and comments.
- [x] The testimonials section is responsive on different devices screen sizes.

**Tasks**

- [x] Create a section in the homepage for testimonials.
- [x] Style the testimonials section using Bootstrap and CSS.
- [x] Use Bootstrap’s grid system to ensure the section is responsive and looks good.
